# Form implementation generated from reading ui file '.\UI File\Exclusion.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmExclusion(object):
    def setupUi(self, frmExclusion):
        frmExclusion.setObjectName("frmExclusion")
        frmExclusion.resize(500, 200)
        font = QtGui.QFont()
        font.setFamily("Mikhak Regular")
        font.setPointSize(10)
        frmExclusion.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/AppIcon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmExclusion.setWindowIcon(icon)
        frmExclusion.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lstExclusion = QtWidgets.QListWidget(parent=frmExclusion)
        self.lstExclusion.setGeometry(QtCore.QRect(10, 10, 260, 180))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lstExclusion.setFont(font)
        self.lstExclusion.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lstExclusion.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.lstExclusion.setObjectName("lstExclusion")
        self.cmbExclusion = QtWidgets.QComboBox(parent=frmExclusion)
        self.cmbExclusion.setGeometry(QtCore.QRect(300, 30, 100, 25))
        self.cmbExclusion.setObjectName("cmbExclusion")
        self.cmbExclusion.addItem("")
        self.cmbExclusion.addItem("")
        self.cmbExclusion.addItem("")
        self.lblExclusion = QtWidgets.QLabel(parent=frmExclusion)
        self.lblExclusion.setGeometry(QtCore.QRect(410, 32, 70, 20))
        self.lblExclusion.setObjectName("lblExclusion")
        self.txtExclusion = QtWidgets.QLineEdit(parent=frmExclusion)
        self.txtExclusion.setGeometry(QtCore.QRect(350, 100, 140, 20))
        self.txtExclusion.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.txtExclusion.setObjectName("txtExclusion")
        self.btnAddExclusion = QtWidgets.QPushButton(parent=frmExclusion)
        self.btnAddExclusion.setGeometry(QtCore.QRect(280, 98, 60, 25))
        self.btnAddExclusion.setObjectName("btnAddExclusion")
        self.btnClearExclusion = QtWidgets.QPushButton(parent=frmExclusion)
        self.btnClearExclusion.setEnabled(False)
        self.btnClearExclusion.setGeometry(QtCore.QRect(410, 165, 75, 25))
        self.btnClearExclusion.setObjectName("btnClearExclusion")
        self.btnDeleteExclusion = QtWidgets.QPushButton(parent=frmExclusion)
        self.btnDeleteExclusion.setEnabled(False)
        self.btnDeleteExclusion.setGeometry(QtCore.QRect(290, 165, 75, 25))
        self.btnDeleteExclusion.setObjectName("btnDeleteExclusion")

        self.retranslateUi(frmExclusion)
        QtCore.QMetaObject.connectSlotsByName(frmExclusion)

    def retranslateUi(self, frmExclusion):
        _translate = QtCore.QCoreApplication.translate
        frmExclusion.setWindowTitle(_translate("frmExclusion", "استثنائات"))
        self.lstExclusion.setToolTip(_translate("frmExclusion", "لیست استثنائات"))
        self.cmbExclusion.setItemText(0, _translate("frmExclusion", "فایل"))
        self.cmbExclusion.setItemText(1, _translate("frmExclusion", "پوشه"))
        self.cmbExclusion.setItemText(2, _translate("frmExclusion", "نوع فایل"))
        self.lblExclusion.setText(_translate("frmExclusion", "نوع استثناء:"))
        self.btnAddExclusion.setToolTip(_translate("frmExclusion", "انتخاب فایل یا پوشه"))
        self.btnAddExclusion.setText(_translate("frmExclusion", "جستجو"))
        self.btnClearExclusion.setToolTip(_translate("frmExclusion", "پاک کردن لیست استثنائات"))
        self.btnClearExclusion.setText(_translate("frmExclusion", "حذف همه"))
        self.btnDeleteExclusion.setToolTip(_translate("frmExclusion", "حذف موارد انتخاب شده در لیست"))
        self.btnDeleteExclusion.setText(_translate("frmExclusion", "حذف"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmExclusion = QtWidgets.QDialog()
    ui = Ui_frmExclusion()
    ui.setupUi(frmExclusion)
    frmExclusion.show()
    sys.exit(app.exec())
